package com.taskflow.taskflow_be.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    UNAUTHORIZED,
    FORBIDDEN,
    USERNAME_TAKEN,
    INVALID_CREDENTIALS,
    NOT_FOUND,
    PROJECT_NOT_FOUND,
    ISSUE_NOT_FOUND,
    BAD_REQUEST,
    INVALID_TOKEN,
    ACCESS_DENIED,
    USER_NOT_FOUND,
    MEMBER_NOT_FOUND,
}
